# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3eefaf565b11768ae083e0a7b1be39b5a3bdf5782828afe3b87179dcd95a60a4763b83ea992d5fc5c60e6f993f270e501bee0a7e33486cb42bf51f6ac3c2f1a5

test:
  secret_key_base: fa654f71ad54f9c9ba2715a2dc01b953c7778c4f15cd83d1a13b9bf357fad3cfcbe8b3f829697d1ea5db2d3b4dd564f5d006fd07bb9dc7b0fe35f6eaf485ab02

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
